const home=document.getElementById("page-home"),achievements=document.getElementById("page-achievements"),space=document.getElementById("page-space"),blog=document.getElementById("page-blog");
function updateActiveNav(page){document.querySelectorAll("[data-route]").forEach(a=>a.classList.toggle("active",a.dataset.route===page))}
function showPage(page,push=true){if(!home)return;[home,achievements,space,blog].forEach(el=>el?.classList.add("hidden"));const target=page==="achievements"?achievements:page==="space"?space:page==="blog"?blog:home;target?.classList.remove("hidden");const safe=target===achievements?"achievements":target===space?"space":target===blog?"blog":"home";updateActiveNav(safe);if(push){const path=safe==="home"?"/":`/${safe}`;if(location.pathname!==path)history.pushState({},"",path)}document.title=safe==="home"?"Hridhaan Sahay — Portfolio":`${safe[0].toUpperCase()+safe.slice(1)} — Hridhaan Sahay`}
document.querySelectorAll("[data-route]").forEach(el=>el.addEventListener("click",e=>{e.preventDefault();showPage(el.dataset.route)}));
window.addEventListener("popstate",()=>showPage(location.pathname.split("/").filter(Boolean)[0]||"home",false));showPage(location.pathname.split("/").filter(Boolean)[0]||"home",false);
document.querySelectorAll("[data-section]").forEach(link=>link.addEventListener("click",e=>{e.preventDefault();const section=document.getElementById(link.dataset.section);showPage("home");setTimeout(()=>section?.scrollIntoView({behavior:"smooth",block:"start"}),40)}));
document.querySelectorAll("[data-space-scroll]").forEach(link=>link.addEventListener("click",e=>{e.preventDefault();document.getElementById("space-gallery")?.scrollIntoView({behavior:"smooth",block:"start"})}));
const menuToggle=document.querySelector(".menu-toggle"),mobileNav=document.querySelector(".mobile-nav");menuToggle?.addEventListener("click",()=>{const open=mobileNav?.classList.toggle("open");menuToggle.setAttribute("aria-expanded",String(Boolean(open)))});mobileNav?.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>mobileNav.classList.remove("open")));
document.getElementById("themeToggle")?.addEventListener("click",()=>document.body.classList.toggle("dim-stars"));
async function loadScrapbookProjects(){const list=document.querySelector(".project-list");if(!list)return;try{const res=await fetch("https://raw.githubusercontent.com/hridhaan-s/scrapbook/main/Data/projects.json",{cache:"no-store"});if(!res.ok)throw new Error(`Scrapbook returned ${res.status}`);const projects=await res.json();const visible=projects.filter(p=>p&&p.title&&p.coverImage&&p.slug);list.innerHTML=visible.map(p=>{const href=`https://scrapbook.hridhaan.me/project.html?slug=${encodeURIComponent(p.slug)}`;const type=p.type||"Project";const description=(p.description||"").split("\n")[0];return `<a class="project-row" href="${href}" target="_blank" rel="noreferrer"><img class="project-cover" src="${p.coverImage}" alt="${escapeHtml(p.title)}" loading="lazy"><div><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(description)}</p></div><span>${escapeHtml(type)}</span><b>↗</b></a>`}).join("")}catch(err){console.error("Scrapbook project sync failed:",err)}}
function escapeHtml(value){return String(value).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]))}loadScrapbookProjects();
async function loadBlog(){const wrap=document.querySelector("#page-blog .blog-wrap");if(!wrap)return;try{const res=await fetch("/blog/posts.json",{cache:"no-store"});if(!res.ok)throw new Error(`Blog data returned ${res.status}`);const posts=(await res.json()).filter(Boolean).sort((a,b)=>new Date(b.date)-new Date(a.date));wrap.innerHTML=posts.map(post=>`<article class="blog-card" data-slug="${escapeHtml(post.slug)}"><div><span class="blog-meta">${escapeHtml(post.displayDate||post.date)} · ${escapeHtml(post.readTime||"5 min read")}</span><h3>${escapeHtml(post.title)}</h3><p>${escapeHtml(post.excerpt||"")}</p></div><button class="read-btn" type="button">Read →</button></article>`).join("");const bySlug=Object.fromEntries(posts.map(p=>[p.slug,p]));wrap.querySelectorAll(".read-btn").forEach(btn=>btn.addEventListener("click",()=>renderPost(bySlug[btn.closest(".blog-card").dataset.slug],wrap)));const requested=new URLSearchParams(location.search).get("post");if(requested&&bySlug[requested])renderPost(bySlug[requested],wrap)}catch(err){console.error("Blog load failed:",err)}}
function renderPost(post,wrap){if(!post)return;const body=(post.sections||[]).map(s=>s.type==="heading"?`<h4>${escapeHtml(s.text)}</h4>`:`<p>${escapeHtml(s.text)}</p>`).join("");wrap.innerHTML=`<article class="blog-post"><span class="blog-meta">${escapeHtml(post.displayDate||post.date)} · ${escapeHtml(post.readTime||"5 min read")}</span><h2>${escapeHtml(post.title)}</h2><button class="back-btn" type="button">← Back to Blog</button>${body}</article>`;wrap.querySelector(".back-btn").addEventListener("click",()=>{history.pushState({},"","/blog");loadBlog()});history.pushState({},"",`/blog?post=${encodeURIComponent(post.slug)}`)}loadBlog();