const home=document.getElementById("page-home"),achievements=document.getElementById("page-achievements"),space=document.getElementById("page-space"),blog=document.getElementById("page-blog");
function updateActiveNav(page){document.querySelectorAll("[data-route]").forEach(a=>a.classList.toggle("active",a.dataset.route===page))}
function showPage(page,push=true){if(!home)return;[home,achievements,space,blog].forEach(el=>el?.classList.add("hidden"));const target=page==="achievements"?achievements:page==="space"?space:page==="blog"?blog:home;target?.classList.remove("hidden");const safe=target===achievements?"achievements":target===space?"space":target===blog?"blog":"home";updateActiveNav(safe);if(push){const path=safe==="home"?"/":`/${safe}`;if(location.pathname!==path)history.pushState({},"",path)}document.title=safe==="home"?"Hridhaan Sahay — Portfolio":`${safe[0].toUpperCase()+safe.slice(1)} — Hridhaan Sahay`}
document.querySelectorAll("[data-route]").forEach(el=>el.addEventListener("click",e=>{e.preventDefault();showPage(el.dataset.route)}));
window.addEventListener("popstate",()=>showPage(location.pathname.split("/").filter(Boolean)[0]||"home",false));showPage(location.pathname.split("/").filter(Boolean)[0]||"home",false);
document.querySelectorAll("[data-section]").forEach(link=>link.addEventListener("click",e=>{e.preventDefault();const section=document.getElementById(link.dataset.section);showPage("home");setTimeout(()=>section?.scrollIntoView({behavior:"smooth",block:"start"}),40)}));
document.querySelectorAll("[data-space-scroll]").forEach(link=>link.addEventListener("click",e=>{e.preventDefault();document.getElementById("space-gallery")?.scrollIntoView({behavior:"smooth",block:"start"})}));
const menuToggle=document.querySelector(".menu-toggle"),mobileNav=document.querySelector(".mobile-nav");menuToggle?.addEventListener("click",()=>{const open=mobileNav?.classList.toggle("open");menuToggle.setAttribute("aria-expanded",String(Boolean(open)))});mobileNav?.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>mobileNav.classList.remove("open")));
document.getElementById("themeToggle")?.addEventListener("click",()=>document.body.classList.toggle("dim-stars"));
async function loadScrapbookProjects(){const list=document.querySelector(".project-list");if(!list)return;try{const res=await fetch("https://raw.githubusercontent.com/hridhaan-s/scrapbook/main/Data/projects.json",{cache:"no-store"});if(!res.ok)throw new Error(`Scrapbook returned ${res.status}`);const projects=await res.json();const visible=projects.filter(p=>p&&p.title&&p.coverImage&&p.slug);list.innerHTML=visible.map(p=>{const href=`https://scrapbook.hridhaan.me/project.html?slug=${encodeURIComponent(p.slug)}`;const type=p.type||"Project";const description=(p.description||"").split("\n")[0];return `<a class="project-row" href="${href}" target="_blank" rel="noreferrer"><img class="project-cover" src="${p.coverImage}" alt="${escapeHtml(p.title)}" loading="lazy"><div><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(description)}</p></div><span>${escapeHtml(type)}</span><b>↗</b></a>`}).join("")}catch(err){console.error("Scrapbook project sync failed:",err)}}
function escapeHtml(value){return String(value).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]))}loadScrapbookProjects();
async function loadBlog(){const wrap=document.querySelector("#page-blog .blog-wrap");if(!wrap)return;try{const res=await fetch("/blog/posts.json",{cache:"no-store"});if(!res.ok)throw new Error(`Blog data returned ${res.status}`);const posts=(await res.json()).filter(Boolean).sort((a,b)=>new Date(b.date)-new Date(a.date));wrap.innerHTML=posts.map(post=>`<article class="blog-card" data-slug="${escapeHtml(post.slug)}"><div><span class="blog-meta">${escapeHtml(post.displayDate||post.date)} · ${escapeHtml(post.readTime||"5 min read")}</span><h3>${escapeHtml(post.title)}</h3><p>${escapeHtml(post.excerpt||"")}</p></div><button class="read-btn" type="button">Read →</button></article>`).join("");const bySlug=Object.fromEntries(posts.map(p=>[p.slug,p]));wrap.querySelectorAll(".read-btn").forEach(btn=>btn.addEventListener("click",()=>renderPost(bySlug[btn.closest(".blog-card").dataset.slug],wrap)));const requested=new URLSearchParams(location.search).get("post");if(requested&&bySlug[requested])renderPost(bySlug[requested],wrap)}catch(err){console.error("Blog load failed:",err)}}
function renderPost(post,wrap){if(!post)return;const body=(post.sections||[]).map(s=>s.type==="heading"?`<h4>${escapeHtml(s.text)}</h4>`:`<p>${escapeHtml(s.text)}</p>`).join("");wrap.innerHTML=`<article class="blog-post"><span class="blog-meta">${escapeHtml(post.displayDate||post.date)} · ${escapeHtml(post.readTime||"5 min read")}</span><h2>${escapeHtml(post.title)}</h2><button class="back-btn" type="button">← Back to Blog</button>${body}</article>`;wrap.querySelector(".back-btn").addEventListener("click",()=>{history.pushState({},"","/blog");loadBlog()});history.pushState({},"",`/blog?post=${encodeURIComponent(post.slug)}`)}loadBlog();

function addSocialRow(){const about=document.getElementById("about");if(!about||document.querySelector(".social-row"))return;const links=[{label:"Email",href:"mailto:hi@Hridhaan.me",icon:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></svg>'},{label:"GitHub",href:"https://github.com/hridhaan-s",icon:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 19c-4 1.2-4-2-5-2m10 4v-3.5c0-1 .1-1.4-.5-2 2-.2 4.1-1 4.1-4.5a3.5 3.5 0 0 0-.9-2.5 3.3 3.3 0 0 0-.1-2.5s-.8-.3-2.6 1a9 9 0 0 0-4.8 0c-1.8-1.3-2.6-1-2.6-1a3.3 3.3 0 0 0-.1 2.5 3.5 3.5 0 0 0-.9 2.5c0 3.5 2.1 4.3 4.1 4.5-.5.5-.6 1-.6 2V21"/></svg>'},{label:"LinkedIn",href:"https://www.linkedin.com/in/hridhaan-sahay",icon:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 9v9M6 6.5v.1M10 18v-5a4 4 0 0 1 8 0v5M10 9v9"/></svg>'},{label:"Slack",href:"https://app.slack.com/client/E09V59WQY1E/",icon:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 4a2 2 0 1 0 0 4h2V4a2 2 0 0 0-2 0Zm6 2a2 2 0 1 0-4 0v2h4a2 2 0 0 0 0-2ZM20 9a2 2 0 1 0-4 0v2h4a2 2 0 0 0 0-2Zm-2 6a2 2 0 1 0-2-2h-2v4a2 2 0 1 0 4-2ZM9 20a2 2 0 1 0 0-4H7v4a2 2 0 0 0 2 0ZM4 15a2 2 0 1 0 4 0v-2H4a2 2 0 0 0 0 2Zm2-6a2 2 0 1 0 2 2h2V7a2 2 0 0 0-4 2Z"/></svg>'},{label:"YouTube",href:"https://www.youtube.com/@Astro-2HR",icon:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="6" width="18" height="12" rx="3"/><path d="m10 9 5 3-5 3z"/></svg>'},{label:"BitBuzz",href:"https://www.youtube.com/@Bitbuzz-club",icon:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 5h10a2 2 0 0 1 2 2v7a2 2 0 0 1-2 2h-5l-4 3v-3H7a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2Z"/><path d="M9 10h6M9 13h4"/></svg>'}];const row=document.createElement("div");row.className="social-row";row.setAttribute("aria-label","Social links");row.innerHTML=links.map(l=>`<a href="${l.href}" ${l.href.startsWith("http")?'target="_blank" rel="noreferrer"':''} aria-label="${l.label}" title="${l.label}">${l.icon}<span>${l.label}</span></a>`).join("");about.insertAdjacentElement("afterend",row)}
addSocialRow();